export const CATEGORY_GROUPS = [
  {
    name: 'Gen AI',
    slug: 'gen-ai',
    icon: '✨',
    description: 'AI-powered creative generation tools',
    subcategories: [
      { name: 'ImageGen', slug: 'image-gen', description: 'Create unique visuals from text prompts' },
      { name: 'ImageEdit', slug: 'image-edit', description: 'Remove backgrounds, enhance & upscale' },
      { name: 'VideoGen', slug: 'video-gen', description: 'Generate cinematic videos from images' },
      { name: 'MusicGen', slug: 'music-gen', description: 'Create original music with AI' },
      { name: 'VoiceGen', slug: 'voice-gen', description: 'Professional AI voiceovers' },
      { name: 'SoundGen', slug: 'sound-gen', description: 'Generate high-quality sound effects' },
      { name: 'GraphicsGen', slug: 'graphics-gen', description: 'Custom icons & illustrations' },
      { name: 'MockupGen', slug: 'mockup-gen', description: 'Realistic product mockups in minutes' },
    ],
  },
  {
    name: 'Video Templates',
    slug: 'video-templates',
    icon: '🎬',
    description: 'Professional video templates for every project',
    subcategories: [
      { name: 'Broadcast Packages', slug: 'broadcast-packages' },
      { name: 'Elements', slug: 'elements' },
      { name: 'Logo Reveals', slug: 'logo-reveals' },
      { name: 'LUTs', slug: 'luts' },
      { name: 'Video Intros', slug: 'video-intros' },
      { name: 'Promos', slug: 'promos' },
      { name: 'Title Sequences', slug: 'title-sequences' },
      { name: 'Infographics', slug: 'infographics' },
      { name: 'Video Displays', slug: 'video-displays' },
    ],
    compatibleTools: ['Premiere Pro', 'After Effects', 'Apple Motion', 'Final Cut Pro', 'DaVinci Resolve'],
    topSearches: ['Logo Animation', 'Text', 'Podcast', 'Mockup', 'Slideshow', 'Lower Thirds', 'Trailer', 'Indian Wedding Invitation'],
  },
  {
    name: 'Stock Video',
    slug: 'stock-video',
    icon: '🎥',
    description: 'High-quality stock footage for any project',
    subcategories: [
      { name: 'Background', slug: 'background' },
      { name: 'Nature', slug: 'nature' },
      { name: 'Business', slug: 'business' },
      { name: 'Woman', slug: 'woman' },
      { name: 'Technology', slug: 'technology' },
      { name: 'People', slug: 'people' },
      { name: 'Man', slug: 'man' },
      { name: 'Travel', slug: 'travel' },
    ],
    topSearches: ['B-roll', 'Resolume', 'VJ Loops', 'Vertical Videos', 'Intro', 'Drone', 'Green Screen', 'Satisfying'],
  },
  {
    name: 'Audio',
    slug: 'audio',
    icon: '🎵',
    description: 'Royalty-free music and sound effects',
    subcategories: [
      { name: 'Logos and Idents', slug: 'logos-and-idents' },
      { name: 'Background Music', slug: 'background-music' },
      { name: 'Epic', slug: 'epic' },
      { name: 'Upbeat', slug: 'upbeat' },
      { name: 'Corporate', slug: 'corporate' },
      { name: 'Happy', slug: 'happy' },
      { name: 'Rock', slug: 'rock' },
      { name: 'Funk', slug: 'funk' },
      { name: 'Gaming SFX', slug: 'gaming-sfx' },
      { name: 'Transitions & Movement', slug: 'transitions-movement' },
      { name: 'Futuristic', slug: 'futuristic' },
      { name: 'Interface', slug: 'interface' },
    ],
    topSearches: ['Movie', 'Podcast Intro', 'Happy Birthday', 'Instagram Reel', 'Devotional', 'Islamic Intro', 'Military Drum', 'Breaking News Intro'],
  },
  {
    name: 'Graphics',
    slug: 'graphics',
    icon: '🎨',
    description: 'Illustrations, icons, textures and more',
    subcategories: [
      { name: 'Objects', slug: 'objects' },
      { name: 'Illustrations', slug: 'illustrations' },
      { name: 'Icons', slug: 'icons' },
      { name: 'Backgrounds', slug: 'backgrounds' },
      { name: 'Textures', slug: 'textures' },
      { name: 'Patterns', slug: 'patterns' },
      { name: 'Actions and Presets', slug: 'actions-presets' },
      { name: 'Brushes', slug: 'brushes' },
      { name: 'Layer Styles', slug: 'layer-styles' },
    ],
    compatibleTools: ['Adobe Photoshop', 'Adobe Illustrator', 'Figma', 'Sketch', 'Affinity'],
    topSearches: ['Food Icons', 'Overlay', 'YouTube', 'Torn Paper', 'Game Assets', 'Logo', 'Dust Overlay', 'Gate'],
  },
  {
    name: 'Design Templates',
    slug: 'design-templates',
    icon: '📐',
    description: 'Print & digital design templates',
    subcategories: [
      { name: 'Graphic Templates', slug: 'graphic-templates' },
      { name: 'Printable Templates', slug: 'printable-templates' },
      { name: 'Product Mockups', slug: 'product-mockups' },
      { name: 'Social Media', slug: 'social-media' },
      { name: 'Websites', slug: 'websites' },
      { name: 'UX/UI Toolkits', slug: 'ux-ui-toolkits' },
      { name: 'Infographics', slug: 'infographics' },
      { name: 'Logos', slug: 'logos' },
      { name: 'Presentations', slug: 'presentations' },
    ],
    compatibleTools: ['Adobe Photoshop', 'Adobe Illustrator', 'Adobe InDesign', 'Affinity', 'Figma', 'Canva', 'Microsoft Word', 'PowerPoint', 'Keynote'],
    topSearches: ['Business Card', 'Brochure', 'Flyer', 'Resume', 'Wedding', 'Branding Presentation', 'Mobile App Presentation', 'Cryptocurrency Presentation'],
  },
  {
    name: 'Photos',
    slug: 'photos',
    icon: '📸',
    description: 'High-resolution stock photography',
    subcategories: [
      { name: 'Background', slug: 'background' },
      { name: 'Office', slug: 'office' },
      { name: 'Business', slug: 'business' },
      { name: 'Sky', slug: 'sky' },
      { name: 'AI', slug: 'ai' },
      { name: 'Paper Texture', slug: 'paper-texture' },
      { name: 'Beach', slug: 'beach' },
      { name: 'Technology', slug: 'technology' },
    ],
    topSearches: ['Wallpaper', 'Animals', 'Balloon Decoration', 'Dog', 'Food', 'Online Video Call', 'Welcome', 'Women'],
  },
  {
    name: '3D',
    slug: '3d',
    icon: '🧊',
    description: '3D models, renders and environments',
    subcategories: [
      { name: 'Models', slug: 'models' },
      { name: 'Templates', slug: 'templates' },
      { name: 'Renders', slug: 'renders' },
      { name: 'Themes', slug: 'themes' },
      { name: 'Nature', slug: 'nature' },
      { name: 'Abstract', slug: 'abstract' },
      { name: 'Transportation', slug: 'transportation' },
      { name: 'Architecture', slug: 'architecture' },
    ],
    compatibleTools: ['Spline', 'Blender'],
    topSearches: ['Car', 'House', 'Tree', 'Chair', 'Table', 'Box', 'Slot Machine', 'Fridges'],
  },
  {
    name: 'Fonts',
    slug: 'fonts',
    icon: '🖋',
    description: 'Premium typefaces for every style',
    subcategories: [
      { name: 'Serif', slug: 'serif' },
      { name: 'Sans-Serif', slug: 'sans-serif' },
      { name: 'Script & Handwritten', slug: 'script-handwritten' },
      { name: 'Decorative', slug: 'decorative' },
    ],
    topSearches: ['Luxury', 'Food', 'Logo', 'Neon', 'Sign Painting', 'Sports', 'Modern', 'Arabic'],
  },
  {
    name: 'Web',
    slug: 'web',
    icon: '🌐',
    description: 'Website templates, themes and plugins',
    subcategories: [
      { name: 'Admin Templates', slug: 'admin-templates' },
      { name: 'Email Templates', slug: 'email-templates' },
      { name: 'Site Templates', slug: 'site-templates' },
      { name: 'Landing Pages', slug: 'landing-pages' },
      { name: 'CMS Templates', slug: 'cms-templates' },
      { name: 'WordPress', slug: 'wordpress' },
      { name: 'Themes', slug: 'themes' },
      { name: 'Plugins', slug: 'plugins' },
      { name: 'Template Kits', slug: 'template-kits' },
      { name: 'Elementor', slug: 'elementor' },
    ],
    topSearches: ['React', 'eCommerce', 'WordPress Blog', 'Event', 'Portfolio', 'WordPress Agency', 'WordPress Ecommerce', 'WordPress Newspaper'],
  },
]

export const AI_TOOLS = [
  {
    name: 'VideoGen',
    slug: 'video-gen',
    description: 'Generate cinematic videos from static images and text prompts.',
    icon: '🎬',
    color: 'from-purple-500 to-pink-500',
  },
  {
    name: 'ImageGen',
    slug: 'image-gen',
    description: 'Create unique visuals in diverse styles using simple text prompts.',
    icon: '🖼️',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    name: 'ImageEdit',
    slug: 'image-edit',
    description: 'Remove backgrounds, erase objects, enhance quality, and upscale.',
    icon: '✏️',
    color: 'from-green-500 to-teal-500',
  },
  {
    name: 'VoiceGen',
    slug: 'voice-gen',
    description: 'Convert text into professional-quality voiceovers with natural AI voices.',
    icon: '🎙️',
    color: 'from-orange-500 to-red-500',
  },
  {
    name: 'MusicGen',
    slug: 'music-gen',
    description: 'Create original music tracks using AI-powered text prompts.',
    icon: '🎵',
    color: 'from-pink-500 to-rose-500',
  },
  {
    name: 'GraphicsGen',
    slug: 'graphics-gen',
    description: 'Create custom icons, illustrations, and graphic assets.',
    icon: '🎨',
    color: 'from-yellow-500 to-orange-500',
  },
  {
    name: 'MockUpGen',
    slug: 'mockup-gen',
    description: 'Design realistic product and branding mockups within minutes.',
    icon: '📱',
    color: 'from-indigo-500 to-purple-500',
  },
  {
    name: 'SoundGen',
    slug: 'sound-gen',
    description: 'Generate high-quality sound effects tailored for your projects.',
    icon: '🔊',
    color: 'from-teal-500 to-green-500',
  },
]
